name: ores_otel_flutter
description: Flutter client for ores-otel
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

