name: ores_otel_flutter
description: Flutter client for ores-otel
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  oresoftware_next_loggers:
    git:
      url: https://github.com/ores-otel/ores.otel.log.git
      ref: 91bf4b8a48773799f10707bf1c6ae7336a393bde
      path: sdk/dart
  rxdart: ^0.28.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
